services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./models:/app/models
      - ./backend:/app/backend
    restart: unless-stopped
    environment:
      - API_NINJAS_KEY=${API_NINJAS_KEY}
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\""]
      interval: 90s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    restart: unless-stopped
